from __future__ import annotations

from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

import pytest

from my_agent.core.events.bus import EventBus
from my_agent.core.llm.base import LLMProvider
from my_agent.core.llm.types import LlmResponse, UsageStats
from my_agent.core.memory.init import InitResult, cmd_init
from my_agent.core.memory.project_init import (
    ProjectInitService,
    ScanLimits,
    scan_project,
)


class _FakeProvider(LLMProvider):
    """A fake LLM provider that returns a controlled JSON response."""

    def __init__(self, response_text: str) -> None:
        self._response_text = response_text
        self.calls: list[dict[str, Any]] = []

    def count_tokens(
        self,
        *,
        messages: list[dict[str, object]],
        tool_schemas: list[dict[str, object]],
        system: str | None = None,
    ) -> int:
        return 0

    def context_window(self) -> int:
        return 64_000

    async def chat(
        self,
        messages: list[dict[str, object]],
        tool_schemas: list[dict[str, object]],
        bus: EventBus,
        run_id: str,
        *,
        step: int = 0,
        system: str | None = None,
    ) -> LlmResponse:
        self.calls.append(
            {
                "messages": messages,
                "tool_schemas": tool_schemas,
                "run_id": run_id,
                "system": system,
            }
        )
        return LlmResponse(
            stop_reason="end_turn",
            text=self._response_text,
            usage=UsageStats(input_tokens=1, output_tokens=1),
        )


def _make_python_project(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / "pyproject.toml").write_text(
        '[project]\nname = "demo"\nversion = "0.1.0"\nrequires-python = ">=3.12"\n',
        encoding="utf-8",
    )
    (root / "uv.lock").write_text("# This file is automatically generated\n", encoding="utf-8")
    (root / "README.md").write_text("# Demo\n\nA Python demo.\n", encoding="utf-8")
    src = root / "src" / "demo"
    src.mkdir(parents=True)
    (src / "__init__.py").write_text("__version__ = '0.1.0'\n", encoding="utf-8")
    tests = root / "tests"
    tests.mkdir()
    (tests / "test_demo.py").write_text("def test_demo(): pass\n", encoding="utf-8")


def _make_node_project(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / "package.json").write_text(
        '{\n  "name": "demo",\n  "version": "1.0.0",\n'
        '  "scripts": {\n    "start": "node src/index.js",\n'
        '    "test": "jest",\n    "build": "tsc"\n  },\n'
        '  "dependencies": {\n    "express": "^4.0.0"\n  }\n}\n',
        encoding="utf-8",
    )
    src = root / "src"
    src.mkdir()
    (src / "index.js").write_text("console.log('hello');\n", encoding="utf-8")
    tests = root / "tests"
    tests.mkdir()
    (tests / "index.test.js").write_text("test('ok', () => {});\n", encoding="utf-8")


def test_scanner_detects_python_project(tmp_path: Path) -> None:
    """Python 项目识别语言、依赖、测试命令和关键目录。"""
    root = tmp_path / "pyproj"
    _make_python_project(root)

    scan = scan_project(root)

    assert scan.language == "python"
    assert "pyproject.toml" in scan.key_files
    assert "uv.lock" in scan.key_files
    assert any("src" in e for e in scan.entries)
    assert any("tests" in e for e in scan.entries)
    assert any("uv sync" in cmd for cmd in scan.commands)
    assert any("pytest" in cmd for cmd in scan.commands)
    assert any("ruff" in cmd for cmd in scan.commands)
    assert any("mypy" in cmd for cmd in scan.commands)


def test_scanner_detects_node_project(tmp_path: Path) -> None:
    """Node 项目识别 manifest scripts 和源码目录。"""
    root = tmp_path / "nodeproj"
    _make_node_project(root)

    scan = scan_project(root)

    assert "node" in scan.language.lower() or "javascript" in scan.language.lower()
    assert "package.json" in scan.key_files
    assert any("src" in e for e in scan.entries)
    assert any("tests" in e for e in scan.entries)
    assert any("npm install" in cmd or "npm ci" in cmd for cmd in scan.commands)
    assert any("npm test" in cmd for cmd in scan.commands)
    assert any("npm start" in cmd for cmd in scan.commands)


def test_scanner_ignores_cache_and_sensitive_files(tmp_path: Path) -> None:
    """忽略 cache、node_modules、runs 和敏感文件。"""
    root = tmp_path / "proj"
    root.mkdir()
    (root / "README.md").write_text("# Proj\n", encoding="utf-8")
    (root / "package.json").write_text('{"name":"proj"}', encoding="utf-8")

    ignored_dirs = [
        ".git",
        ".venv",
        "venv",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "node_modules",
        "runs",
        "dist",
        "build",
    ]
    for name in ignored_dirs:
        (root / name).mkdir(exist_ok=True)
        (root / name / "file.txt").write_text("secret", encoding="utf-8")

    sensitive_files = [".env", "secret.pem", "credentials.json", "api.key", "id_rsa"]
    for name in sensitive_files:
        (root / name).write_text("sk-abc123", encoding="utf-8")

    scan = scan_project(root)

    for name in ignored_dirs:
        assert name + "/" not in scan.entries, f"{name} should be ignored"
    for name in sensitive_files:
        assert name not in scan.entries, f"{name} should be ignored"

    # Ignored directories appear in skipped; sensitive files also listed there.
    skipped_names = {note.split(":", 1)[0] for note in scan.skipped}
    for name in ignored_dirs:
        assert name in skipped_names, f"{name} should be listed as skipped"
    for name in sensitive_files:
        assert name in skipped_names, f"{name} should be listed as skipped"

    for name in sensitive_files:
        assert any(name in p for p in scan.sensitive_paths), f"{name} should be sensitive"

    for content in scan.file_contents.values():
        assert "sk-abc123" not in content


def test_scanner_size_limits(tmp_path: Path) -> None:
    """扫描大小边界：超限时仍能完成并给出 skipped。"""
    root = tmp_path / "proj"
    root.mkdir()
    (root / "small.txt").write_text("small", encoding="utf-8")
    (root / "medium.txt").write_text("x" * 100, encoding="utf-8")
    (root / "large.txt").write_text("x" * 1000, encoding="utf-8")

    limits = ScanLimits(max_file_size=50, max_total_bytes=80, max_files=2)
    scan = scan_project(root, limits=limits)

    total = sum(len(c.encode("utf-8")) for c in scan.file_contents.values())
    assert total <= limits.max_total_bytes
    assert len(scan.file_contents) <= limits.max_files
    assert any("large.txt" in note or "size" in note.lower() for note in scan.notes)


def test_scanner_detects_top_level_docs_and_readme(tmp_path: Path) -> None:
    root = tmp_path / "proj"
    root.mkdir()
    (root / "README.md").write_text("# Proj\n", encoding="utf-8")
    docs = root / "docs"
    docs.mkdir()
    (docs / "guide.md").write_text("guide", encoding="utf-8")

    scan = scan_project(root)
    assert "README.md" in scan.key_files
    assert any("docs" in e for e in scan.entries)
    assert "README.md" in scan.file_contents


async def test_service_fallback_without_provider(tmp_path: Path) -> None:
    """provider 不可用时仍生成基础结果。"""
    root = tmp_path / "proj"
    _make_python_project(root)

    service = ProjectInitService(root, provider=None)
    result = await service.run()

    assert isinstance(result, InitResult)
    assert (root / ".my-agent" / "context.md").is_file()
    assert (root / "AGENTS.md").is_file()

    context = (root / ".my-agent" / "context.md").read_text(encoding="utf-8")
    assert "python" in context.lower()
    assert "pyproject.toml" in context
    assert "uv sync" in context
    assert "confirmed" in context.lower() or "needs verification" in context.lower()

    agents = (root / "AGENTS.md").read_text(encoding="utf-8")
    assert "MY-AGENT:BEGIN" in agents
    assert "MY-AGENT:END" in agents


async def test_service_invalid_provider_does_not_overwrite_existing_files(tmp_path: Path) -> None:
    """provider 输出非法时不覆盖现有文件。"""
    root = tmp_path / "proj"
    _make_python_project(root)

    (root / ".my-agent").mkdir()
    (root / ".my-agent" / "context.md").write_text("PRESERVED_CONTEXT", encoding="utf-8")
    (root / "AGENTS.md").write_text("PRESERVED_AGENTS\n", encoding="utf-8")

    bad_provider = _FakeProvider("this is not valid json")
    service = ProjectInitService(root, provider=bad_provider)
    result = await service.run()

    assert "failed" in result.status.lower() or "fallback" in result.status.lower()
    assert (root / ".my-agent" / "context.md").read_text(encoding="utf-8") == "PRESERVED_CONTEXT"
    assert "PRESERVED_AGENTS" in (root / "AGENTS.md").read_text(encoding="utf-8")


async def test_service_preserves_agents_md_marker_content(tmp_path: Path) -> None:
    """已有 AGENTS.md 的 marker 外内容保持不变。"""
    root = tmp_path / "proj"
    _make_python_project(root)

    user_before = "# User Guide\n\nKeep this.\n"
    user_after = "\n## Footer\n\nAlso keep.\n"
    marker = "<!-- MY-AGENT:BEGIN -->\nold managed content\n<!-- MY-AGENT:END -->\n"
    (root / "AGENTS.md").write_text(user_before + marker + user_after, encoding="utf-8")

    service = ProjectInitService(root, provider=None)
    await service.run()

    content = (root / "AGENTS.md").read_text(encoding="utf-8")
    assert user_before.strip() in content
    assert "Footer" in content
    assert "Also keep" in content
    assert content.count("<!-- MY-AGENT:BEGIN -->") == 1


async def test_service_no_duplicate_markers_on_rerun(tmp_path: Path) -> None:
    """重复运行不重复插入 marker。"""
    root = tmp_path / "proj"
    _make_python_project(root)

    service = ProjectInitService(root, provider=None)
    await service.run()
    await service.run()

    content = (root / "AGENTS.md").read_text(encoding="utf-8")
    assert content.count("<!-- MY-AGENT:BEGIN -->") == 1
    assert content.count("<!-- MY-AGENT:END -->") == 1


async def test_service_generates_content_with_confirmed_and_inferred_labels(tmp_path: Path) -> None:
    """生成内容区分 confirmed、inferred 和 needs verification。"""
    root = tmp_path / "proj"
    _make_python_project(root)

    good_provider = _FakeProvider(
        "{\n"
        '  "project_summary": "A Python demo project.",\n'
        '  "languages_and_frameworks": "python",\n'
        '  "repository_structure": "src/demo, tests/",\n'
        '  "key_files": "pyproject.toml, uv.lock",\n'
        '  "commands": "uv sync --dev; uv run pytest",\n'
        '  "architecture_notes": "Standard src layout.",\n'
        '  "coding_conventions": "Use ruff and mypy.",\n'
        '  "testing_notes": "Run pytest.",\n'
        '  "generated_or_sensitive_paths": ".venv, runs",\n'
        '  "known_unknowns": "CI pipeline details."\n'
        "}"
    )
    service = ProjectInitService(root, provider=good_provider)
    await service.run()

    context = (root / ".my-agent" / "context.md").read_text(encoding="utf-8")
    labels = ("confirmed", "inferred", "needs verification")
    assert any(label in context.lower() for label in labels)

    # Provider should have received the scan summary, not raw secrets.
    assert len(good_provider.calls) == 1
    prompt_text = str(good_provider.calls[0]["messages"])
    assert "sk-" not in prompt_text


async def test_service_output_does_not_contain_secrets(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """输出不包含 secrets。"""
    root = tmp_path / "proj"
    _make_python_project(root)
    (root / ".env").write_text("DEEPSEEK_API_KEY=sk-secret-value\n", encoding="utf-8")
    monkeypatch.setenv("DEEPSEEK_API_KEY", "sk-secret-value")

    service = ProjectInitService(root, provider=None)
    await service.run()

    context = (root / ".my-agent" / "context.md").read_text(encoding="utf-8")
    agents = (root / "AGENTS.md").read_text(encoding="utf-8")
    assert "sk-secret-value" not in context
    assert "sk-secret-value" not in agents
    assert "DEEPSEEK_API_KEY" not in context
    assert "DEEPSEEK_API_KEY" not in agents


def test_cli_cmd_init_uses_project_init_service(monkeypatch: pytest.MonkeyPatch) -> None:
    """CLI `my-agent init` 复用 project-init service。"""
    calls: list[tuple[Path, LLMProvider | None]] = []

    async def _recording_run(self: ProjectInitService) -> InitResult:
        calls.append((self.root, self.provider))
        return InitResult(messages=["ok"], files_created=[], files_updated=[], status="success")

    monkeypatch.setattr(ProjectInitService, "run", _recording_run)

    cmd_init()

    assert len(calls) == 1
    assert calls[0][0] == Path.cwd()


async def test_tui_init_branch_uses_project_init_service(monkeypatch: pytest.MonkeyPatch) -> None:
    """TUI `/init` 复用同一个 ProjectInitService。"""
    from my_agent.tui import app as tui_app

    calls: list[tuple[Path, LLMProvider | None]] = []

    async def _recording_run(self: ProjectInitService) -> InitResult:
        calls.append((self.root, self.provider))
        return InitResult(messages=["ok"], files_created=[], files_updated=[], status="success")

    monkeypatch.setattr(ProjectInitService, "run", _recording_run)

    class _FakeLog:
        lines: list[str] = []

        def write(self, text: str) -> None:
            self.lines.append(text)

    class _FakeStatus:
        activities: list[str] = []

        def set_activity(self, activity: str, detail: str = "") -> None:
            self.activities.append(activity)

        def finish(self, status: str) -> None:
            self.activities.append(f"finish:{status}")

    class _FakePalette:
        display = False

        def close(self) -> None:
            pass

    chat_calls: list[tuple[str, str]] = []

    async def _fake_add_chat(role: str, content: str) -> MagicMock:
        chat_calls.append((role, content))
        return MagicMock()

    app = tui_app.MyAgentTuiApp("127.0.0.1", 7437)
    app._busy = False
    app._client = None  # type: ignore[assignment]
    app._session_id = None  # type: ignore[assignment]

    log = _FakeLog()
    status = _FakeStatus()

    def _fake_query_one(selector: str, widget_type: type[Any] | None = None) -> Any:
        if selector == "#log":
            return log
        if selector == "#run-status":
            return status
        if selector == "#slash-palette":
            return _FakePalette()
        return MagicMock()

    monkeypatch.setattr(app, "query_one", _fake_query_one)
    monkeypatch.setattr(app, "_clear_prompt", lambda: None)
    monkeypatch.setattr(app, "_focus_prompt", lambda: None)
    monkeypatch.setattr(app, "_add_chat", _fake_add_chat)

    await app._submit_prompt_text("/init")

    assert len(calls) == 1
    assert calls[0][0] == Path.cwd()
    assert any("init" in a or "analyz" in a.lower() for a in status.activities)
    assert any("ok" in line for line in log.lines)
    assert ("user", "/init") in chat_calls
